### ISSUE TITLE
ASTCreator crashes on missing .tostring file

### ISSUE THREAD

**Issue by peterwvj** [overturetool/astcreator#7]
Given a specification `demo.ast`. If `demo.ast.tostring` is missing then ASTCreator crashes brutally. See output below.

~~~
[INFO] ------------------------------------------------------------------------
[INFO] Building ASTCreator String Bug 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- astcreator-plugin:1.6.4:generate (java) @ stringbug ---
[INFO] Preparing for tree generation...
[INFO] Checking if generation required.
[INFO] Full AST generation needed
[INFO] Generating...
[INFO] Generator starting with input: /home/peter/dev/playground/string-bug/src/main/resources/demo.ast
[ERROR] 
java.io.FileNotFoundException: /home/peter/dev/playground/string-bug/src/main/resources/demo.ast.tostring (No such file or directory)
	at java.io.FileInputStream.open(Native Method) ~[na:1.7.0_79]
	at java.io.FileInputStream.<init>(FileInputStream.java:146) ~[na:1.7.0_79]
	at org.overture.tools.maven.astcreator.GenerateTree.generateSingleAst(GenerateTree.java:332) [astcreator-plugin-1.6.4.jar:na]
	at org.overture.tools.maven.astcreator.GenerateTree.execute(GenerateTree.java:153) [astcreator-plugin-1.6.4.jar:na]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.3.3.jar:3.3.3]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) [maven-core-3.3.3.jar:3.3.3]
~~~

**Comment by peterwvj** [comment]
If the `tostring` file is missing ASTCreator should create an empty version of this file
